### ISSUE TITLE
Migrate to pyproject.toml for modern packaging and editable installs

### ISSUE THREAD

**Issue by mcyc** [mcyc/mufasa#227]
Legacy editable installs (via `setup.py develop`) are deprecated and will be removed in pip 25.0. To future-proof the project and align with modern packaging standards, we need to migrate to using a `pyproject.toml` file as per [PEP 660](https://peps.python.org/pep-0660/). This ensures compatibility with current and future versions of `pip` and `setuptools`.

**Proposed Steps**:
1. Add a `pyproject.toml` file with a minimal configuration:
    ```toml
    [build-system]
    requires = ["setuptools>=64", "wheel"]
    build-backend = "setuptools.build_meta"
    ```
2. Test the installation workflow:
    - Ensure editable installs (`pip install -e .`) work as expected.
    - Update documentation if necessary.
3. Remove reliance on legacy `setup.py` workflows in the future.

**References**:
- [PEP 660](https://peps.python.org/pep-0660/)
- [pip issue #11457](https://github.com/pypa/pip/issues/11457)
